/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package belajar.kotlin.unit.test

import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.*

class AppTest {
    @Test fun testAppHasAGreeting() {
        println("Ini Test")
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "should have a greeting")
    }
}
